In [1]:
import numpy as np
import pandas as pd

z_values = [-5, -2, -1, 0, 1, 2, 5]
p_values = 1 / (1 + np.exp(-np.array(z_values)))

df_sigmoid = pd.DataFrame({
    "score_z": z_values,
    "probability": p_values
})

df_sigmoid

   score_z  probability
0       -5     0.006693
1       -2     0.119203
2       -1     0.268941
3        0     0.500000
4        1     0.731059
5        2     0.880797
6        5     0.993307

In [4]:
#Odds Table
probabilities = [0.1, 0.3, 0.5, 0.7, 0.9]

odds_table = pd.DataFrame({
    "probability": probabilities
})

odds_table["odds"] = odds_table["probability"] / (1 - odds_table["probability"])

odds_table

   probability      odds
0          0.1  0.111111
1          0.3  0.428571
2          0.5  1.000000
3          0.7  2.333333
4          0.9  9.000000